version: '3'

services:
  postgres:
    build: ./postgres
    restart: always
    #image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/betsys_data
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        PGDATA: /var/lib/postgresql/data/betsys_data
    
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
    pgdata:
